class Question {
  final String text;
  final List<String> options;
  final int correctAnswerIndex;

  Question({
    required this.text,
    required this.options,
    required this.correctAnswerIndex,
  });
}

final List<Question> allQuestions = [
  Question(text: "Como se declara uma variável cujo tipo é inferido automaticamente no Dart?", options: ["let", "var", "auto", "dynamic"], correctAnswerIndex: 1),
  Question(text: "Qual palavra-chave é usada no Dart para permitir que uma variável aceite o valor nulo?", options: ["null_ok", "optional", "? (ponto de interrogação)", "Any"], correctAnswerIndex: 2),
  Question(text: "Qual estrutura de repetição itera sobre os elementos de uma lista diretamente?", options: ["for", "while", "do-while", "for-in"], correctAnswerIndex: 3),
  Question(text: "O que é um Mixin no Dart?", options: ["Uma forma de herança múltipla estrita", "Um jeito de reutilizar código em várias hierarquias de classes", "Um tipo de variável", "Um banco de dados"], correctAnswerIndex: 1),
  Question(text: "No Dart, como chamamos uma função que não tem nome?", options: ["Função fantasma", "Função void", "Função anônima (ou lambda)", "Função abstrata"], correctAnswerIndex: 2),
  Question(text: "Qual coleção no Dart armazena valores únicos (sem repetições)?", options: ["List", "Map", "Set", "Array"], correctAnswerIndex: 2),
  Question(text: "Qual coleção armazena dados no formato chave-valor?", options: ["List", "Set", "Tuple", "Map"], correctAnswerIndex: 3),
  Question(text: "A palavra 'dynamic' no Dart significa que:", options: ["O tipo não pode mudar", "O tipo é verificado em tempo de execução e pode mudar", "A variável é constante", "A variável é nula"], correctAnswerIndex: 1),
  Question(text: "O que o modificador 'late' garante ao compilador?", options: ["Que a variável será inicializada antes de ser lida", "Que a variável vai atrasar a execução", "Que a variável é assíncrona", "Que a variável será destruída"], correctAnswerIndex: 0),
  Question(text: "Como capturamos erros em operações assíncronas (Future) no Dart?", options: ["catch()", "onException()", "catchError() ou try/catch", "throwError()"], correctAnswerIndex: 2),
  Question(text: "Qual widget é usado para detectar gestos na tela, como toques simples ou duplos?", options: ["TouchDetector", "GestureDetector", "TapWidget", "ActionDetector"], correctAnswerIndex: 1),
  Question(text: "Qual widget cria um efeito visual de 'onda' (ripple) ao ser tocado?", options: ["InkWell", "RippleWidget", "WaveButton", "TapEffect"], correctAnswerIndex: 0),
  Question(text: "Se você quiser sobrepor um texto a uma imagem, qual widget de layout você usa?", options: ["Column", "Row", "Stack", "Overlay"], correctAnswerIndex: 2),
  Question(text: "Qual widget usamos para exibir imagens da internet?", options: ["Image.network", "Image.asset", "Image.web", "NetImage"], correctAnswerIndex: 0),
  Question(text: "Para que serve o widget 'Flexible'?", options: ["Para deixar o texto em negrito", "Para animar a tela", "Para redimensionar um widget filho dentro de uma Row ou Column", "Para ignorar toques na tela"], correctAnswerIndex: 2),
  Question(text: "Qual widget é comumente usado como botão flutuante no canto inferior direito?", options: ["ElevatedButton", "FloatingActionButton", "IconButton", "BottomButton"], correctAnswerIndex: 1),
  Question(text: "Como criamos um campo de entrada de texto para o usuário digitar?", options: ["Text", "InputBox", "TextField", "KeyboardWidget"], correctAnswerIndex: 2),
  Question(text: "Qual widget exibe uma barra de progresso circular?", options: ["LinearProgressIndicator", "CircularProgressIndicator", "LoadingCircle", "Spinner"], correctAnswerIndex: 1),
  Question(text: "Para que serve o widget 'SingleChildScrollView'?", options: ["Exibir um único texto", "Criar um carrossel de imagens", "Permitir rolagem quando o conteúdo ultrapassa o tamanho da tela", "Bloquear a rolagem da tela"], correctAnswerIndex: 2),
  Question(text: "Qual widget usamos para desenhar formas personalizadas do zero?", options: ["PainterWidget", "Canvas", "CustomPaint", "ShapeDraw"], correctAnswerIndex: 2),
  Question(text: "Como criar uma lista onde os itens são gerados sob demanda (lazy loading)?", options: ["ListView.builder", "Column", "GridView.count", "List.generate"], correctAnswerIndex: 0),
  Question(text: "Qual widget cria uma grade bidimensional (linhas e colunas)?", options: ["Table", "GridView", "MatrixWidget", "GridBox"], correctAnswerIndex: 1),
  Question(text: "Para que serve o widget 'Hero'?", options: ["Dar superpoderes ao app", "Criar botões invisíveis", "Animar um widget que voa de uma tela para outra", "Tocar sons de vitória"], correctAnswerIndex: 2),
  Question(text: "Como esconder um widget na tela sem removê-lo da árvore?", options: ["Visibility", "HiddenWidget", "Opacity(0)", "Ambas: Visibility ou Opacity(0)"], correctAnswerIndex: 3),
  Question(text: "Qual widget exibe uma mensagem temporária na parte inferior da tela?", options: ["Dialog", "SnackBar", "Toast", "BottomSheet"], correctAnswerIndex: 1),
  Question(text: "No Flutter, como chamamos o objeto que gerencia o histórico de telas?", options: ["RouterManager", "ScreenController", "Navigator", "HistoryKeeper"], correctAnswerIndex: 2),
  Question(text: "Como definimos rotas nomeadas na configuração do MaterialApp?", options: ["paths: {}", "routes: {}", "pages: {}", "screens: {}"], correctAnswerIndex: 1),
  Question(text: "Para navegar para uma rota nomeada, usamos:", options: ["Navigator.pushNamed", "Navigator.go", "Navigator.route", "Navigator.send"], correctAnswerIndex: 0),
  Question(text: "O que o Navigator.pushReplacement faz?", options: ["Abre duas telas", "Substitui a tela atual pela nova na pilha de navegação", "Limpa toda a memória", "Recarrega a tela atual"], correctAnswerIndex: 1),
  Question(text: "Qual pacote externo do Google se tornou padrão para navegação avançada e deep links no Flutter Web?", options: ["go_router", "auto_route", "fluro", "nav_web"], correctAnswerIndex: 0),
  Question(text: "Qual classe é frequentemente usada com Provider para notificar a UI sobre mudanças de estado?", options: ["StateNotifier", "ChangeNotifier", "ValueUpdater", "UIController"], correctAnswerIndex: 1),
  Question(text: "Qual padrão de gerenciamento de estado usa Streams, Sinks e Events?", options: ["Provider", "GetX", "BLoC (Business Logic Component)", "MobX"], correctAnswerIndex: 2),
  Question(text: "Quem é o autor do popular pacote de gerência de estado 'Riverpod'?", options: ["Felix Angelov", "Remi Rousselet", "Filip Hracek", "Simon Lightfoot"], correctAnswerIndex: 1),
  Question(text: "Qual pacote oferece gerência de estado, injeção de dependência e navegação de forma simplificada e sem contexto?", options: ["GetX", "Redux", "Provider", "Bloc"], correctAnswerIndex: 0),
  Question(text: "O que o widget 'FutureBuilder' faz?", options: ["Constrói widgets com base no resultado de uma operação assíncrona", "Gera o futuro do app", "Transforma código legado em moderno", "Atrasa o carregamento da tela"], correctAnswerIndex: 0),
  Question(text: "O que o widget 'StreamBuilder' faz?", options: ["Assiste a vídeos em tempo real", "Reconstrói a UI a cada novo dado emitido por um Stream", "Faz download em segundo plano", "Gera dados aleatórios"], correctAnswerIndex: 1),
  Question(text: "Qual classe gerencia o valor, o tempo e o status de uma animação explícita no Flutter?", options: ["AnimManager", "Tween", "AnimationController", "Ticker"], correctAnswerIndex: 2),
  Question(text: "O que é um 'Tween' em animações do Flutter?", options: ["Um widget animado", "Um objeto que interpola (calcula os valores) entre um início e um fim", "Um efeito sonoro", "Um temporizador"], correctAnswerIndex: 1),
  Question(text: "Qual a diferença entre Animações Implícitas e Explícitas?", options: ["Implícitas são mais fáceis (ex: AnimatedContainer), explícitas dão mais controle", "Não há diferença", "Implícitas não funcionam no iOS", "Explícitas são apenas para jogos 3D"], correctAnswerIndex: 0),
  Question(text: "Se você quiser que uma caixa mude de cor e tamanho suavemente ao trocar as variáveis, qual widget é ideal?", options: ["Container", "AnimatedContainer", "TweenBox", "MotionWidget"], correctAnswerIndex: 1),
  Question(text: "Quais são as três árvores principais (trees) que o Flutter usa nos bastidores?", options: ["Widget, RenderObject e Node", "Widget, Element e RenderObject", "State, UI e Logic", "Dart, C++ e Skia"], correctAnswerIndex: 1),
  Question(text: "Qual é o motor de renderização (graphics engine) originalmente usado pelo Flutter?", options: ["Unity", "Unreal", "Skia", "Impeller"], correctAnswerIndex: 2),
  Question(text: "Qual é o nome do novo motor de renderização desenvolvido para substituir o Skia, melhorando a performance no iOS?", options: ["Vulkan", "Impeller", "Metal", "React"], correctAnswerIndex: 1),
  Question(text: "O que significa FFI no contexto de Dart/Flutter?", options: ["Foreign Function Interface (para chamar código C nativo)", "Fast Flutter Integration", "Flutter Firebase Index", "Future Function Identifier"], correctAnswerIndex: 0),
  Question(text: "Como definimos regras estritas de formatação e boas práticas no projeto?", options: ["No arquivo pubspec.yaml", "No arquivo analysis_options.yaml", "No arquivo main.dart", "No arquivo config.json"], correctAnswerIndex: 1),
  Question(text: "Para usar um pacote de ícones personalizados, onde devemos declará-lo?", options: ["Na pasta lib", "No arquivo pubspec.yaml", "Direto no terminal", "No AndroidManifest.xml"], correctAnswerIndex: 1),
  Question(text: "O que faz o comando 'flutter clean'?", options: ["Apaga o projeto", "Formata o código fonte", "Deleta as pastas de build e cache do projeto", "Desinstala o Flutter do PC"], correctAnswerIndex: 2),
  Question(text: "Como o Flutter se comunica nativamente com o Android ou iOS (Bluetooth, Câmera, etc)?", options: ["Method Channels", "API REST", "Bluetooth Direct", "Dart Native"], correctAnswerIndex: 0),
  Question(text: "O que é o DevTools no ecossistema Flutter?", options: ["Um pacote de UI", "Uma suíte de ferramentas para debugar, analisar performance e inspecionar a UI", "Um site de documentação", "Um emulador de Android"], correctAnswerIndex: 1),
  Question(text: "Qual comando compila um aplicativo para distribuição na Google Play Store?", options: ["flutter build apk", "flutter build appbundle", "flutter export android", "flutter release run"], correctAnswerIndex: 1),
  Question(text: "O que é um Isolate no Dart?", options: ["Uma classe isolada", "A forma do Dart executar código em paralelo (threads próprias com memória separada)", "Um widget invisível", "Um erro fatal"], correctAnswerIndex: 1),
  Question(text: "Como adicionamos novos métodos a uma classe existente (como String) sem alterá-la diretamente?", options: ["Usando Mixins", "Usando Inheritance", "Usando Extensions (extension on...)", "Usando Interfaces"], correctAnswerIndex: 2),
  Question(text: "No contexto de listas, o que o método .map() faz?", options: ["Abre o Google Maps", "Transforma cada item da lista retornando uma nova lista iterável", "Filtra itens nulos", "Apaga a lista"], correctAnswerIndex: 1),
  Question(text: "O que acontece se chamarmos setState() fora de um StatefulWidget?", options: ["A tela pisca", "O app fica mais rápido", "Erro, pois StatelessWidget não tem estado mutável", "Nada acontece"], correctAnswerIndex: 2),
  Question(text: "No pubspec.yaml, o que o circunflexo (^) antes da versão de um pacote significa (ex: ^1.2.0)?", options: ["Versão exata obrigatória", "Pode usar versões compatíveis (até < 2.0.0)", "Apenas versões beta", "Ignorar essa dependência"], correctAnswerIndex: 1),
  Question(text: "Qual widget permite criar efeitos de rolagem avançados, como app bars que encolhem e listas complexas misturadas?", options: ["Sliver (ex: CustomScrollView)", "ListView", "ComplexColumn", "ScrollMaster"], correctAnswerIndex: 0),
  Question(text: "O que o construtor 'factory' faz no Dart?", options: ["Sempre retorna uma nova instância do zero", "Permite retornar uma instância em cache ou de um subtipo em vez de sempre criar uma nova", "Gera código automático", "Cria fábricas de widgets"], correctAnswerIndex: 1),
  Question(text: "Qual banco de dados local NoSQL é famoso por ser extremamente rápido e gravado em Dart puro?", options: ["SQLite", "Firebase", "Hive", "PostgreSQL"], correctAnswerIndex: 2),
  Question(text: "O que é Firebase no ecossistema de apps?", options: ["Uma linguagem de programação", "Uma plataforma do Google que oferece backend como serviço (Auth, Firestore, etc)", "Um plugin de animação", "O servidor de hospedagem do Flutter"], correctAnswerIndex: 1),
  Question(text: "Ao final de tudo, qual é o lema não-oficial de construção de UI no Flutter?", options: ["Tudo é um Objeto", "Tudo é um Widget", "Tudo é um Element", "Escreva uma vez, rode em qualquer lugar"], correctAnswerIndex: 1),
  Question(text: "Qual widget você usaria para aplicar um recorte arredondado em uma imagem?", options: ["RoundBox", "CircleAvatar", "ClipRRect", "BorderRadiusWidget"], correctAnswerIndex: 2),
  Question(text: "Como você agrupa múltiplos widgets lado a lado, mas se não couber na tela eles quebram para a linha de baixo?", options: ["Row", "Wrap", "Flow", "GridRow"], correctAnswerIndex: 1),
  Question(text: "Qual classe usamos para formatar datas em texto legível (requer o pacote intl)?", options: ["DateFormatter", "DateFormat", "TimeText", "DateTime.format"], correctAnswerIndex: 1),
  Question(text: "Como evitamos que o teclado do celular cubra o campo de texto no qual estamos digitando?", options: ["É automático se usarmos Scaffold / SingleChildScrollView", "Desativamos o teclado", "Usamos Margin(100)", "O Flutter não suporta isso"], correctAnswerIndex: 0),
  Question(text: "Qual a extensão do arquivo principal de código fonte no Flutter?", options: [".flutter", ".dt", ".dart", ".java"], correctAnswerIndex: 2),
];